[package]
name = "protobuf"
version = "0.0.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2018"

[dependencies]
bytes = { version = "1", default-features = false }
prost = { path = ".." }
prost-types = { path = "../prost-types" }

[build-dependencies]
anyhow = "1"
curl = "0.4"
flate2 = "1.0"
# Whatever crate depends on this one is responsible for enabling either
# `prost-build/protoc-vendored-bin` or `prost-build/protoc-vendored`.
prost-build = { path = "../prost-build", default-features = false }
tar = "0.4"
tempfile = "3"

[dev-dependencies]
criterion = "0.3"
cfg-if = "1"

[lib]
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[bench]]
name = "dataset"
harness = false
